networks:
  movies_app: {}

services:
  webclient:
    restart: always

    build:
      context: ./movies-app-webclient
      dockerfile: Dockerfile

    ports:
      - "3000:3000"

    volumes:
      - ./movies-app-webclient:/app

    networks:
      - movies_app

  api:
    restart: always

    build:
      context: ./movies-app-api
      dockerfile: Dockerfile

    ports:
      - "3001:3001"

    volumes:
      - ./movies-app-api:/app

    networks:
      - movies_app

    env_file:
      - .env

  mongodb:
    image: mongo:7.0

    restart: always

    ports:
      - "27017:27017"

    networks:
      - movies_app

    env_file:
      - .env
